#!/usr/bin/env python3
import gi
gi.require_version("Gtk", "4.0")
from gi.repository import Gtk

from window import MainWindow


class AINoteApp(Gtk.Application):
    def __init__(self):
        super().__init__(application_id="com.ainote.app")
        self.connect("activate", self.on_activate)

    def on_activate(self, app):
        win = MainWindow(application=app)
        win.present()


def main():
    app = AINoteApp()
    app.run()


if __name__ == "__main__":
    main()
